global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3002']

  - job_name: 'call-service'
    static_configs:
      - targets: ['call-service:3003']

  - job_name: 'signaling-service'
    static_configs:
      - targets: ['signaling-service:3004']

  - job_name: 'media-service'
    static_configs:
      - targets: ['media-service:3005']
